# Generated by Django 5.0.2 on 2024-04-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('opinion', models.CharField(max_length=100)),
            ],
        ),
    ]
